default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_DATABASE_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] + '_test'%>

production:
  <<: *default